###
POST http://localhost:3977/api/v1/users/user HTTP/1.1
Content-Type: application/json

{
  "name": "Ricardo",
  "lastName": "Kaká",
  "email": "ricardo@hotmail.com",
  "password": "ricardo9876",
  "active": true
}

###
GET http://localhost:3977/api/v1/users HTTP/1.1

###
GET http://localhost:3977/api/v1/users/ HTTP/1.1

###
PUT http://localhost:3977/api/v1/users/ HTTP/1.1
Content-Type: application/json

{
  "name": "Ricardo",
  "lastName": "Dos Santos"
}

###
DELETE  http://localhost:3977/api/v1/users/ HTTP/1.1